package constants

const (
	LogRequestStarted       = "request started"
	LogRequestCompleted     = "request completed"
	LogAuthRegister         = "User registration requested"
	LogAuthLogin            = "User login requested"
	LogUserProfileRead      = "User profile read"
	LogUserProfileUpdated   = "User profile updated"
	LogMoodCreated          = "Mood created with mood_level and mood_tags"
	LogMoodListed           = "Mood list requested"
	LogMoodUpdated          = "Mood updated"
	LogMoodDeleted          = "Mood deleted"
	LogMoodTrend            = "Mood trend calculated"
	LogAssessmentListed     = "Assessment list requested"
	LogAssessmentCreated    = "Assessment created"
	LogAssessmentTaken      = "Assessment submitted"
	LogAssessmentResult     = "Assessment result generated"
	LogJournalCreated       = "Journal created"
	LogJournalListed        = "Journal list requested"
	LogJournalUpdated       = "Journal updated"
	LogJournalDeleted       = "Journal deleted"
	LogAuditWrite           = "audit write action"
	LogDBConnected          = "database connected"
	LogDBMigrated           = "database migrated"
	LogHealthChecked        = "health check completed"
	LogErrorWrapped         = "application error wrapped"
	LogSeeded               = "sample assessments seeded"
	LogPlanCreated          = "AdjustmentPlan created with 7 days and input_hash"
	LogPlanCreatedDedup     = "AdjustmentPlan create deduplicated to existing active plan"
	LogPlanRecomputed       = "AdjustmentPlan future days recomputed to a new version"
	LogPlanRecomputeSkipped = "AdjustmentPlan recompute skipped after source change"
	LogPlanStatusChanged    = "AdjustmentPlan lifecycle status changed by action"
	LogPlanAutoCompleted    = "AdjustmentPlan auto-completed after all days finished"
	LogPlanTaskChanged      = "PlanTask status or handwritten content changed"
	LogPlanTaskAdded        = "PlanTask custom handwritten task added"
	LogPlanDayNoted         = "PlanDay handwritten note saved"
	LogPlanReportFallback   = "AdjustmentPlan frozen report unreadable, fallback to live build"
	LogPlanListed           = "AdjustmentPlan detail or list requested"
)
